[versions]
agp = "8.7.0"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.10.1"
constraintlayout = "2.1.4"
composeBom = "2024.06.00"
activityCompose = "1.9.0"
okhttp = "4.12.0"
lifecycleRuntimeCompose = "2.8.3"
lifecycleViewmodelCompose = "2.8.3"
retrofit2KotlinxSerializationConverter = "1.0.0"
ui = "1.10.0-beta02"
material3 = "1.5.0-alpha08"
lifecycleViewmodelComposeVersion = "2.10.0-rc01"
foundation = "1.9.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
compose-bom = { group = "implementation(platform(", name = "compose-bom", version.ref = "composeBom" }
activity-compose = { group = "implementation(", name = "activity-compose", version.ref = "activityCompose" }
okhttp = { group = "implementation(", name = "okhttp", version.ref = "okhttp" }
lifecycle-runtime-compose = { group = "implementation(", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
lifecycle-viewmodel-compose = { group = "implementation(", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
retrofit2-kotlinx-serialization-converter = { group = "implementation(", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelComposeVersion" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

